### ISSUE TITLE
mdns issue

### ISSUE THREAD

**Issue by Deepdelver** [hass-emulated-hue/core#144]
I'm running hassio core: core-2021.3.4
installed by installation instructions. 

Can you help me find what is going wrong here? 

'''
[Errno 2] No such file or directory: '/config/hass-emulated-hue/emulated_hue.json'
2021-03-31 23:56:17,915 INFO  emulated_hue.config -- Auto detected listen IP address is 192.168.1.251
2021-03-31 23:56:17,922 DEBUG getmac -- Raw MAC found: None
2021-03-31 23:56:17,923 DEBUG getmac -- Raw MAC found: ca:a5:8a:c3:3d:a0
2021-03-31 23:56:17,923 DEBUG aiorun -- Entering run()
2021-03-31 23:56:17,925 DEBUG aiorun -- Creating default executor
2021-03-31 23:56:17,931 INFO  hass_client -- Connected to Home Assistant ws (version 2021.3.4)
2021-03-31 23:56:17,962 INFO  emulated_hue.api -- Started HTTP webserver on port 80
2021-03-31 23:56:17,976 INFO  emulated_hue.api -- Started HTTPS webserver on port 443
2021-03-31 23:56:17,977 DEBUG emulated_hue.discovery -- Starting mDNS/uPNP discovery broadcast...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/app/emulated_hue/discovery.py", line 126, in run
    ssdp_socket.bind(("", 1900))
OSError: [Errno 98] Address already in use
'''

**Comment by alexyao2015** [comment]
This isn't a bug. Start a discussion. You have something else running on the part as described in the logs.
