### ISSUE TITLE
Error in logs  ERROR asyncio -- Task exception was never retrieved

### ISSUE THREAD

**Issue by simplenotezy** [hass-emulated-hue/core#162]
**Describe the bug**

I see the following error in console.

**Steps to Reproduce**
1. Start addon
2. See the error

**Expected behavior**
No error

**Logs**

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-set-vars.sh: executing... 
[cont-init.d] 00-set-vars.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:21:25] INFO: Starting Emulated Hue...
2021-06-13 15:21:29,473 INFO  emulated_hue.config -- Auto detected listen IP address is 192.168.39.122
2021-06-13 15:21:29,685 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.8/site-packages/aiorun.py:219> exception=CannotConnect("502, message='Invalid response status', url=URL('ws://hassio/homeassistant/api/websocket')")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/hass_client/client.py", line 241, in connect
    self._client = await self._http_session.ws_connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 769, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 502, message='Invalid response status', url=URL('ws://hassio/homeassistant/api/websocket')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiorun.py", line 229, in new_coro
    await coro
  File "/app/emulated_hue/__init__.py", line 54, in async_start
    await self._hass.connect()
  File "/usr/local/lib/python3.8/site-packages/hass_client/client.py", line 257, in connect
    raise CannotConnect(err) from err
hass_client.exceptions.CannotConnect: 502, message='Invalid response status', url=URL('ws://hassio/homeassistant/api/websocket')
```

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
 - Addon version (Ex: stable or dev): stable
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): hassio
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): raspberry pi 3

**Additional context**

**Comment by alexyao2015** [comment]
If you read the error, you can see it can't connect to the hassio websocket for some reason. I would go diagnose that issue by trying to fix the internal websocket connection first. Maybe restarting home assistant, asking the home assistant forums/discord, or reinstalling from scratch. If you can reproduce this from a clean install, it may be worth looking into, however ATM this is not a bug with the addon.

**Comment by simplenotezy** [comment]
Thanks for promt reply @alexyao2015 😊 it ended up working, after a restart
