### ISSUE TITLE
Endless lights and switches

### ISSUE THREAD

**Issue by alanpi** [hass-emulated-hue/core#173]
**Describe the bug**

iam getting endless amount of the same lights.
It creates every seconde the same light again and again

**Steps to Reproduce**
Clean install

**Expected behavior**

**Logs**

**Hardware Info:**
 - Architecture (Ex: x86, ARM): arm
 - Addon version (Ex: stable or dev): dev and stable
 - OS (Ex: Windows 10, Ubuntu Buster): hassio 6.6 core 7.4
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Additional context**

**Comment by alexyao2015** [comment]
Logs?

**Comment by alanpi** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/config/hass-emulated-hue/emulated_hue.json' -> '/config/hass-emulated-hue/emulated_hue.json.backup'
2021-07-24 20:49:52,026 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/api.py", line 80, in wrapped_func
    if not username or not await cls.config.async_get_user(username):
  File "/app/emulated_hue/config.py", line 286, in async_get_user
    await self.async_set_storage_value("users", username, user_data)
  File "/app/emulated_hue/config.py", line 245, in async_set_storage_value
    await async_save_json(self.get_path(CONFIG_FILE), self._config)
  File "/app/emulated_hue/utils.py", line 121, in async_save_json
    return await loop.run_in_executor(None, save_json, filename, data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/emulated_hue/utils.py", line 128, in save_json
    os.replace(filename, safe_copy)

**Comment by alanpi** [comment]
Sorry my bad thought I can add hue integration from home assistant

**Comment by alexyao2015** [comment]
That would definitely create endless lights because it's importing lights from itself...
