### ISSUE TITLE
Locked Up a Few Times

### ISSUE THREAD

**Issue by dcmeglio** [hass-emulated-hue/core#354]
**Describe the bug**
My lights became unresponsive. Only solution I've found is to restart the addon

**Steps to Reproduce**

Unsure. Just seems to happen after a while

**Expected behavior**

Lights should function properly

**Logs**

```
    return await func(cls, request)
  File "/app/emulated_hue/apiv1.py", line 145, in async_get_lights
    return send_json_response(await self.__async_get_all_lights())
  File "/app/emulated_hue/apiv1.py", line 780, in __async_get_all_lights
    for entity_id in self.ctl.controller_hass.get_entities():
  File "/app/emulated_hue/controllers/homeassistant.py", line 115, in get_entities
    return [entity["entity_id"] for entity in self.items_by_domain(domain)]
  File "/app/emulated_hue/controllers/homeassistant.py", line 115, in <listcomp>
    return [entity["entity_id"] for entity in self.items_by_domain(domain)]
TypeError: 'NoneType' object is not subscriptable
2022-10-15 20:40:40,466 DEBUG emulated_hue.apiv1 -- [192.168.1.34] GET /api/mIp6SmaWQu2u-vWKbDOvl42pgadTn5hewY44t4Y4/lights
2022-10-15 20:40:40,468 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/apiv1.py", line 72, in wrapped_func
    return await func(cls, request)
  File "/app/emulated_hue/apiv1.py", line 145, in async_get_lights
    return send_json_response(await self.__async_get_all_lights())
  File "/app/emulated_hue/apiv1.py", line 780, in __async_get_all_lights
    for entity_id in self.ctl.controller_hass.get_entities():
  File "/app/emulated_hue/controllers/homeassistant.py", line 115, in get_entities
    return [entity["entity_id"] for entity in self.items_by_domain(domain)]
  File "/app/emulated_hue/controllers/homeassistant.py", line 115, in <listcomp>
    return [entity["entity_id"] for entity in self.items_by_domain(domain)]
TypeError: 'NoneType' object is not subscriptable
2022-10-15 20:40:41,936 DEBUG emulated_hue.apiv1 -- [192.168.1.34] GET /api/mIp6SmaWQu2u-vWKbDOvl42pgadTn5hewY44t4Y4/lights
2022-10-15 20:40:41,940 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/apiv1.py", line 72, in wrapped_func
    return await func(cls, request)
  File "/app/emulated_hue/apiv1.py", line 145, in async_get_lights
    return send_json_response(await self.__async_get_all_lights())
  File "/app/emulated_hue/apiv1.py", line 780, in __async_get_all_lights
    for entity_id in self.ctl.controller_hass.get_entities():
  File "/app/emulated_hue/controllers/homeassistant.py", line 115, in get_entities
    return [entity["entity_id"] for entity in self.items_by_domain(domain)]
  File "/app/emulated_hue/controllers/homeassistant.py", line 115, in <listcomp>
    return [entity["entity_id"] for entity in self.items_by_domain(domain)]
TypeError: 'NoneType' object is not subscriptable
2022-10-15 20:41:43,572 DEBUG emulated_hue.apiv1 -- [192.168.1.34] GET /api/mIp6SmaWQu2u-vWKbDOvl42pgadTn5hewY44t4Y4/lights
2022-10-15 20:41:43,573 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/apiv1.py", line 72, in wrapped_func
    return await func(cls, request)
  File "/app/emulated_hue/apiv1.py", line 145, in async_get_lights
    return send_json_response(await self.__async_get_all_lights())
  File "/app/emulated_hue/apiv1.py", line 780, in __async_get_all_lights
    for entity_id in self.ctl.controller_hass.get_entities():
  File "/app/emulated_hue/controllers/homeassistant.py", line 115, in get_entities
    return [entity["entity_id"] for entity in self.items_by_domain(domain)]
  File "/app/emulated_hue/controllers/homeassistant.py", line 115, in <listcomp>
    return [entity["entity_id"] for entity in self.items_by_domain(domain)]
TypeError: 'NoneType' object is not subscriptable
2022-10-15 20:41:45,046 DEBUG emulated_hue.apiv1 -- [192.168.1.34] GET /api/mIp6SmaWQu2u-vWKbDOvl42pgadTn5hewY44t4Y4/lights
2022-10-15 20:41:45,048 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/apiv1.py", line 72, in wrapped_func
    return await func(cls, request)
  File "/app/emulated_hue/apiv1.py", line 145, in async_get_lights
    return send_json_response(await self.__async_get_all_lights())
  File "/app/emulated_hue/apiv1.py", line 780, in __async_get_all_lights
    for entity_id in self.ctl.controller_hass.get_entities():
  File "/app/emulated_hue/controllers/homeassistant.py", line 115, in get_entities
    return [entity["entity_id"] for entity in self.items_by_domain(domain)]
  File "/app/emulated_hue/controllers/homeassistant.py", line 115, in <listcomp>
    return [entity["entity_id"] for entity in self.items_by_domain(domain)]
TypeError: 'NoneType' object is not subscriptable
2022-10-15 20:41:46,510 DEBUG emulated_hue.apiv1 -- [192.168.1.34] GET /api/mIp6SmaWQu2u-vWKbDOvl42pgadTn5hewY44t4Y4/lights
2022-10-15 20:41:46,513 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/apiv1.py", line 72, in wrapped_func
    return await func(cls, request)
  File "/app/emulated_hue/apiv1.py", line 145, in async_get_lights
    return send_json_response(await self.__async_get_all_lights())
  File "/app/emulated_hue/apiv1.py", line 780, in __async_get_all_lights
    for entity_id in self.ctl.controller_hass.get_entities():
  File "/app/emulated_hue/controllers/homeassistant.py", line 115, in get_entities
    return [entity["entity_id"] for entity in self.items_by_domain(domain)]
  File "/app/emulated_hue/controllers/homeassistant.py", line 115, in <listcomp>
    return [entity["entity_id"] for entity in self.items_by_domain(domain)]
TypeError: 'NoneType' object is not subscriptable
```

**Hardware Info:**
 - Architecture (Ex: x86, ARM): ARM
 - Addon version (Ex: stable or dev):  dev
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster):  HAOS
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero):  rPi 4

**Additional context**

**Comment by alexyao2015** [comment]
I think this should fix it. Can you give it a try? `fix/issue/354`

**Comment by dcmeglio** [comment]
I installed it. I don't actually know how to reproduce the issue, just seemed to happen over time, so I'll just let it sit for a week or two and report back.
