### ISSUE TITLE
Hue official & Hue Essentials app entertainment rooms broken - requires obligated update

### ISSUE THREAD

**Issue by MeshDigital** [hass-emulated-hue/core#430]
### Description

When using the officlal Hue app or Hue Essentials app to use an entertainment zone to combine official and non official entertainment lights, its not possible to set up.
Both apps say there is a new required version of the HUE system that must be installled on the bridge

### Expected behavior

should be able to use the official  app/ hue essentials app

### Reproduction steps

just did a fresh install on PI 3B+ with latest vesion of Homeassistant & Has emulated hue
when trying to link  official app > error that hub needs to be updated
Hue essentials app does connect, but when trying o set a scene on and create antertainment room we get issues

### Relevant log output

```shell
nothing found really besides the log from HA

    resp = await handler(request)
  File "/app/emulated_hue/apiv1.py", line 72, in wrapped_func
    return await func(cls, request)
  File "/app/emulated_hue/apiv1.py", line 475, in get_full_state
    "lights": await self.__async_get_all_lights(),
  File "/app/emulated_hue/apiv1.py", line 780, in __async_get_all_lights
    for entity_id in self.ctl.controller_hass.get_entities():
  File "/app/emulated_hue/controllers/homeassistant.py", line 116, in get_entities
    entity["entity_id"] for entity in self.items_by_domain(domain) if entity
  File "/usr/local/lib/python3.10/site-packages/hass_client/client.py", line 175, in items_by_domain
    raise NotConnected("Please call connect first.")
hass_client.exceptions.NotConnected: Please call connect first.
2023-04-18 16:51:10,009 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/apiv1.py", line 71, in wrapped_func
    return await func(cls, request, request_data)
  File "/app/emulated_hue/apiv1.py", line 272, in async_group_action
    await self.__async_light_action(entity_id, request_data)
  File "/app/emulated_hue/apiv1.py", line 654, in __async_light_action
    await call.async_execute()
  File "/app/emulated_hue/controllers/devices.py", line 158, in async_execute
    await self._device.async_execute(self.control_state)
  File "/app/emulated_hue/controllers/devices.py", line 315, in async_execute
    await self.ctl.controller_hass.async_turn_off(self._entity_id)
  File "/app/emulated_hue/controllers/homeassistant.py", line 31, in async_turn_off
    await self.call_service(HASS_DOMAIN_HOMEASSISTANT, HASS_SERVICE_TURN_OFF, data)
  File "/usr/local/lib/python3.10/site-packages/hass_client/client.py", line 205, in call_service
    raise NotConnected("Please call connect first.")
hass_client.exceptions.NotConnected: Please call connect first.
2023-04-18 16:51:12,093 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/apiv1.py", line 71, in wrapped_func
    return await func(cls, request, request_data)
  File "/app/emulated_hue/apiv1.py", line 272, in async_group_action
    await self.__async_light_action(entity_id, request_data)
  File "/app/emulated_hue/apiv1.py", line 654, in __async_light_action
    await call.async_execute()
  File "/app/emulated_hue/controllers/devices.py", line 158, in async_execute
    await self._device.async_execute(self.control_state)
  File "/app/emulated_hue/controllers/devices.py", line 311, in async_execute
    await self.ctl.controller_hass.async_turn_on(
  File "/app/emulated_hue/controllers/homeassistant.py", line 41, in async_turn_on
    await self.call_service(HASS_DOMAIN_HOMEASSISTANT, HASS_SERVICE_TURN_ON, data)
  File "/usr/local/lib/python3.10/site-packages/hass_client/client.py", line 205, in call_service
    raise NotConnected("Please call connect first.")
hass_client.exceptions.NotConnected: Please call connect first.
2023-04-18 16:51:13,108 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/apiv1.py", line 71, in wrapped_func
    return await func(cls, request, request_data)
  File "/app/emulated_hue/apiv1.py", line 272, in async_group_action
    await self.__async_light_action(entity_id, request_data)
  File "/app/emulated_hue/apiv1.py", line 654, in __async_light_action
    await call.async_execute()
  File "/app/emulated_hue/controllers/devices.py", line 158, in async_execute
    await self._device.async_execute(self.control_state)
  File "/app/emulated_hue/controllers/devices.py", line 311, in async_execute
    await self.ctl.controller_hass.async_turn_on(
  File "/app/emulated_hue/controllers/homeassistant.py", line 41, in async_turn_on
    await self.call_service(HASS_DOMAIN_HOMEASSISTANT, HASS_SERVICE_TURN_ON, data)
  File "/usr/local/lib/python3.10/site-packages/hass_client/client.py", line 205, in call_service
    raise NotConnected("Please call connect first.")
hass_client.exceptions.NotConnected: Please call connect first.
2023-04-18 16:52:23,769 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/apiv1.py", line 72, in wrapped_func
    return await func(cls, request)
  File "/app/emulated_hue/apiv1.py", line 475, in get_full_state
    "lights": await self.__async_get_all_lights(),
  File "/app/emulated_hue/apiv1.py", line 780, in __async_get_all_lights
    for entity_id in self.ctl.controller_hass.get_entities():
  File "/app/emulated_hue/controllers/homeassistant.py", line 116, in get_entities
    entity["entity_id"] for entity in self.items_by_domain(domain) if entity
  File "/usr/local/lib/python3.10/site-packages/hass_client/client.py", line 175, in items_by_domain
    raise NotConnected("Please call connect first.")
hass_client.exceptions.NotConnected: Please call connect first.
2023-04-18 16:52:28,006 INFO  emulated_hue.controllers.config -- Link mode is disabled.
2023-04-18 16:52:52,746 INFO  hass_client -- Connected to Home Assistant ws (version 2023.4.5)
2023-04-18 16:54:34,985 INFO  emulated_hue.controllers.config -- Link mode is disabled.
2023-04-18 16:59:33,770 INFO  emulated_hue.controllers.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2023-04-18 16:59:39,679 INFO  emulated_hue.controllers.config -- Link mode is enabled for the next 5 minutes.
2023-04-18 16:59:40,035 INFO  emulated_hue.apiv1 -- Client Hue Essentials#SM-S906B registered
2023-04-18 16:59:40,036 INFO  emulated_hue.controllers.config -- Link mode is disabled.
2023-04-18 17:04:39,680 INFO  emulated_hue.controllers.config -- Link mode is disabled.
```

### Operating system

Other

### Install method

HassOS Addon

### Version

0.3

### Any other information that may be helpful

easily reproducible

**Comment by tsloms** [comment]
same issue here with non-dev add-on version 0.3.0 fresh install

**Comment by criticallimit** [comment]
same here. first install and update in hue app is required. not possible to complete to link hue hub with the hue account.

is there someone working on this?

**Comment by computergreek** [comment]
issue still present here too

**Comment by onefckcps** [comment]
i get this error on a fresh installation of HA too.

**Comment by jsenecal** [comment]
Please see https://github.com/hass-emulated-hue/core/discussions/228#discussioncomment-2002926

**Comment by fanaticDavid** [comment]
This issue has not been solved yet, afaik.

**Comment by senna1992** [comment]
still persistent for new installations

**Comment by cibrenvenuti** [comment]
Same issue here. Due to lack of updates, I think this project, unfortunally, is definetly dead :'(

**Comment by fanaticDavid** [comment]
The whole project should be marked as stale these days. It is unusable.
