### ISSUE TITLE
Addon won't start on new repository

### ISSUE THREAD

**Issue by Mr-Groch** [hass-emulated-hue/core#47]
Rpi 3b+ 32 bit

I have updated repository to https://github.com/hass-emulated-hue/hassio-repo and tried beta and stable addon, after trying to start only this will log and it interrupts:

```
/init: 11: /init: /bin/importas: Exec format error
/init: 12: export: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: bad variable name
```

dev doesn't build:

```
21-01-04 15:05:25 INFO (SyncWorker_2) [supervisor.docker.addon] Starting build for 7c966942/armv7-addon-emulated-hue-dev:dev
21-01-04 15:06:06 ERROR (SyncWorker_2) [supervisor.docker.addon] Can't build 7c966942/armv7-addon-emulated-hue-dev:dev: The command '/bin/sh -c wget -O base.tar.gz https://github.com/hass-emulated-hue/s6-overlay-base/archive/master.tar.gz     && /base     && tar zxvf base.tar.gz --strip 1 -C /base' returned a non-zero code: 127
21-01-04 15:06:06 ERROR (SyncWorker_2) [supervisor.docker.addon] Build log:
Step 1/11 : FROM alpine:latest as downloader
 ---> 857a3eeeed97
Step 2/11 : RUN wget -O base.tar.gz https://github.com/hass-emulated-hue/s6-overlay-base/archive/master.tar.gz     && /base     && tar zxvf base.tar.gz --strip 1 -C /base
 ---> Running in 23e31f5f8f20
Connecting to github.com (140.82.121.3:443)

Connecting to codeload.github.com (140.82.121.9:443)

saving to 'base.tar.gz'

base.tar.gz          100% |********************************|  1360  0:00:00 ETA
'base.tar.gz' saved

/bin/sh: /base: not found

Removing intermediate container 23e31f5f8f20

21-01-04 15:06:06 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-10609592' coro=<Job.__call__.<locals>.wrapper() done, defined at /usr/src/supervisor/supervisor/jobs/decorator.py:38> exception=AddonsError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 413, in _build
    image, log = self.sys_docker.images.build(
  File "/usr/local/lib/python3.8/site-packages/docker/models/images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c wget -O base.tar.gz https://github.com/hass-emulated-hue/s6-overlay-base/archive/master.tar.gz     && /base     && tar zxvf base.tar.gz --strip 1 -C /base' returned a non-zero code: 127
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 182, in install
    await addon.instance.install(store.version, store.image)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 400, in _install
    self._build(tag)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 433, in _build
    raise DockerError() from err
supervisor.exceptions.DockerError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 63, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 61, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 185, in install
    raise AddonsError() from err
supervisor.exceptions.AddonsError
```

**Comment by alexyao2015** [comment]
Can you try both the stable and dev versions again? If it doesn't work, please let me know.

**Comment by alexyao2015** [comment]
Would you able to be able to ssh into the machine and run `docker images` followed by `docker image inspect [container id]`? This will help confirm my suspicions relating to incorrect arch pulls.

**Comment by Mr-Groch** [comment]
For stable - the same problem as before, and this is inspect output:

```
[
    {
        "Id": "sha256:920339769e5e2928b94024ed4ed44200e7abedfc233c5c1a3df7b8f388b2f853",
        "RepoTags": [
            "ghcr.io/hass-emulated-hue/core:0.0.11"
        ],
        "RepoDigests": [
            "ghcr.io/hass-emulated-hue/core@sha256:db0a4ad70f55aa15047894e2ba13e16a4186517b650308b3ddce7b91ed4d7661"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2021-01-04T06:59:43.964767335Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.8.7",
                "PYTHON_PIP_VERSION=20.3.3",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5f38681f7f5872e4032860b54e9cc11cf0374932/get-pip.py",
                "PYTHON_GET_PIP_SHA256=6a0b13826862f33c13b614a921d36253bfa1ae779c5fbf569876f3585057e9d2",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=2",
                "S6_KEEP_ENV=1",
                "DEBIAN_FRONTEND=noninteractive",
                "DEBUG=false",
                "VERBOSE=false",
                "HASS_URL=",
                "HASS_TOKEN="
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "io.hass.arch": "armhf",
                "io.hass.description": "Hue Emulation for Home Assistant",
                "io.hass.name": "Hass Emulated Hue",
                "io.hass.type": "addon",
                "io.hass.version": "0.0.11"
            }
        },
        "Architecture": "arm",
        "Os": "linux",
        "Size": 135604734,
        "VirtualSize": 135604734,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/mnt/data/docker/overlay2/446fa575f46b2d7b40f2c3aa0928352a76ed84290c8c2993997a54802273213e/diff:/mnt/data/docker/overlay2/a929ef68ac2da9848aec9760fe58a62d7752f99d121e2631bde9ea583d636b6f/diff:/mnt/data/docker/overlay2/6de78b5a80497da5ee45b2a71fc42ed0dad3adde10fbd939a52a1ca6a26c5be5/diff:/mnt/data/docker/overlay2/28860c045578cfa16d0a7026e3f8780736750b8b272c342de7f69bba795b11af/diff:/mnt/data/docker/overlay2/7d24aa8791797e6bc2f60e872ced5ef98989536d35c365c7d24e2d394fd9d3d0/diff:/mnt/data/docker/overlay2/b7215146c6fcf23d0d1c2171b8cd3318ebbf2d928625c125dbccd8391c37052b/diff:/mnt/data/docker/overlay2/0a3e071de0531a83d67e39ed763bfae147eb72aa4032182472dc891283274ac1/diff:/mnt/data/docker/overlay2/4a654c2b431d31386cbff8a86b9d3d533cf6c5b08effe85bc812b5b597bbbd8e/diff:/mnt/data/docker/overlay2/849cd5cc77787539c0bdc0b825e1a61e77403fb2eafb534dbfcb8c63178600bd/diff:/mnt/data/docker/overlay2/0b2345040d6cd7e854032fde88d9626ae350f4ee98cf494be7dbb1fd79c3fcf4/diff:/mnt/data/docker/overlay2/e0f0641fec5928a3fcec6f5da1eaf7ee3f63e968f1d1abf69e1b323ed41b940f/diff",
                "MergedDir": "/mnt/data/docker/overlay2/5a019a013bfc258f5972ae98e22a4b2f2b176cef2ff7bba170e25d6c48aa8633/merged",
                "UpperDir": "/mnt/data/docker/overlay2/5a019a013bfc258f5972ae98e22a4b2f2b176cef2ff7bba170e25d6c48aa8633/diff",
                "WorkDir": "/mnt/data/docker/overlay2/5a019a013bfc258f5972ae98e22a4b2f2b176cef2ff7bba170e25d6c48aa8633/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:b2922aff2910c1ed4b92a0710eb0d901d5d8c424225c4197f03ca4b5081cb460",
                "sha256:d9bdc92c409970aa9de880fd8533c5a88688eb5dc417f80c40de3e413b83c1ab",
                "sha256:06120e97db792ba2abdf5c1e3f17cdf88672a9144c6c5a1b99a618c6fa5713f9",
                "sha256:c3c2520b0b72893d63c2646d364f567d480980535f43ee03230edef2de1d4225",
                "sha256:20eb78acf957f0bdca07be0e75143a1ee1baa8107448d07092f548512089ce28",
                "sha256:6e2e0a3ea073ff9b5e22158645f27c9da3ca3375b03a3ef60cc702084a395bc3",
                "sha256:e38e041e0557d58af558584301ace1ff461ed648c991b9f2852a8da955b61b44",
                "sha256:6b3128b65677070d6595753ad99afd86f00bdb3bff6a5412a4ea284c781e0675",
                "sha256:42c061a6e34eeed7905190d7ed8ad0b488d9f1a4b7ccaa603a116b88af7a3130",
                "sha256:caa2682c573718c0f20eaebec740dc3cdf1dd94cbc0a2eb3fbd724acc3786944",
                "sha256:d147cdd53964c5d3d98127696d7fd418c6647d3f265ed4fc80a4c4f3c3058c94",
                "sha256:6762661e976156faca9a42b91df91c7891a1570f70d1318b2be47c7c4369b9e1"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

dev branch build successfully this time, but same error on start like on stable, inspect on dev image:

```
[
    {
        "Id": "sha256:264d36f3aaa517abf3c6f9253eacac27f5ea250420a7c51848dcba21ef92fcc4",
        "RepoTags": [
            "7c966942/armv7-addon-emulated-hue-dev:dev"
        ],
        "RepoDigests": [],
        "Parent": "sha256:6312eec6caf0c922635bafdbc57700cf75f1ec1fe6dfd8fc8012dcb9eaa3baab",
        "Comment": "",
        "Created": "2021-01-04T20:35:54.122981094Z",
        "Container": "8c55825c7bb5d0b9c24b819f53b87d6537457a3dee6fb1b2b62ebe6cd03f9f4f",
        "ContainerConfig": {
            "Hostname": "8c55825c7bb5",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.8.7",
                "PYTHON_PIP_VERSION=20.3.3",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5f38681f7f5872e4032860b54e9cc11cf0374932/get-pip.py",
                "PYTHON_GET_PIP_SHA256=6a0b13826862f33c13b614a921d36253bfa1ae779c5fbf569876f3585057e9d2",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=2",
                "S6_KEEP_ENV=1",
                "DEBIAN_FRONTEND=noninteractive"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "LABEL io.hass.version=dev"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:6312eec6caf0c922635bafdbc57700cf75f1ec1fe6dfd8fc8012dcb9eaa3baab",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "io.hass.arch": "armv7",
                "io.hass.description": "Hue Emulation for Home Assistant",
                "io.hass.name": "Emulated HUE (dev)",
                "io.hass.type": "addon",
                "io.hass.url": "https://github.com/hass-emulated-hue/core",
                "io.hass.version": "dev"
            }
        },
        "DockerVersion": "19.03.13",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
                "PYTHON_VERSION=3.8.7",
                "PYTHON_PIP_VERSION=20.3.3",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/5f38681f7f5872e4032860b54e9cc11cf0374932/get-pip.py",
                "PYTHON_GET_PIP_SHA256=6a0b13826862f33c13b614a921d36253bfa1ae779c5fbf569876f3585057e9d2",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=2",
                "S6_KEEP_ENV=1",
                "DEBIAN_FRONTEND=noninteractive"
            ],
            "Cmd": [
                "/init"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:6312eec6caf0c922635bafdbc57700cf75f1ec1fe6dfd8fc8012dcb9eaa3baab",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "io.hass.arch": "armv7",
                "io.hass.description": "Hue Emulation for Home Assistant",
                "io.hass.name": "Emulated HUE (dev)",
                "io.hass.type": "addon",
                "io.hass.url": "https://github.com/hass-emulated-hue/core",
                "io.hass.version": "dev"
            }
        },
        "Architecture": "arm",
        "Os": "linux",
        "Size": 135505074,
        "VirtualSize": 135505074,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/mnt/data/docker/overlay2/195f30cdf89afaac16d598ff62a2ef6eccb02f732cd86143bd47d7da19b49935/diff:/mnt/data/docker/overlay2/ac05f537d3294e2ec2bfe68055730327194d85e01fd4f7e402e661a74fcee96a/diff:/mnt/data/docker/overlay2/fd57ea5e514e5dc9e8a465f8c5c3df2c0838b078ca894041306b68302dccd337/diff:/mnt/data/docker/overlay2/20befe32685f819cb3045e5e2af28f30c2285807bac79f6aa5c88310f4694f50/diff:/mnt/data/docker/overlay2/612273b205424326895c8ba7d8739486579e380515e8674ca87730e0c64c3c48/diff:/mnt/data/docker/overlay2/21345274e64a22747cc5c216a9b524bdafe5dbf06905ad774536c895b5dc13f8/diff:/mnt/data/docker/overlay2/a76c3523b0cd4989d6de26fac2957121b49f2a2464e33b1a111854b94aff78f4/diff:/mnt/data/docker/overlay2/0d191983978ec494ddf682da8f4553e6099ee08a021d47c70fd5fcd0971ffacd/diff:/mnt/data/docker/overlay2/fb8314fca0d2b10df8e6aadc777f6ec44212b6f205a021fbf5524b081d9b46c9/diff:/mnt/data/docker/overlay2/1e174b6a4cb14aabe36355b9519a9f5921d2a2bc74a4ea37b7529d946fd9eedb/diff:/mnt/data/docker/overlay2/e0f0641fec5928a3fcec6f5da1eaf7ee3f63e968f1d1abf69e1b323ed41b940f/diff",
                "MergedDir": "/mnt/data/docker/overlay2/c5913ab47df6155662d707c539770ae697b3be3c6e7ed818188697ef8d9cc3f7/merged",
                "UpperDir": "/mnt/data/docker/overlay2/c5913ab47df6155662d707c539770ae697b3be3c6e7ed818188697ef8d9cc3f7/diff",
                "WorkDir": "/mnt/data/docker/overlay2/c5913ab47df6155662d707c539770ae697b3be3c6e7ed818188697ef8d9cc3f7/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:b2922aff2910c1ed4b92a0710eb0d901d5d8c424225c4197f03ca4b5081cb460",
                "sha256:d9bdc92c409970aa9de880fd8533c5a88688eb5dc417f80c40de3e413b83c1ab",
                "sha256:06120e97db792ba2abdf5c1e3f17cdf88672a9144c6c5a1b99a618c6fa5713f9",
                "sha256:c3c2520b0b72893d63c2646d364f567d480980535f43ee03230edef2de1d4225",
                "sha256:20eb78acf957f0bdca07be0e75143a1ee1baa8107448d07092f548512089ce28",
                "sha256:6e2e0a3ea073ff9b5e22158645f27c9da3ca3375b03a3ef60cc702084a395bc3",
                "sha256:e38e041e0557d58af558584301ace1ff461ed648c991b9f2852a8da955b61b44",
                "sha256:6b3128b65677070d6595753ad99afd86f00bdb3bff6a5412a4ea284c781e0675",
                "sha256:42c061a6e34eeed7905190d7ed8ad0b488d9f1a4b7ccaa603a116b88af7a3130",
                "sha256:caa2682c573718c0f20eaebec740dc3cdf1dd94cbc0a2eb3fbd724acc3786944",
                "sha256:7c86e772e4fecd9204aa5bf1d2033613a1c766ebbee8014dbfe35943e59759eb",
                "sha256:2e7d3e03e5a8bab7eac85bcabb292e8fed4f652bf331fd3475c700999885bdcb"
            ]
        },
        "Metadata": {
            "LastTagTime": "2021-01-04T20:35:56.790190261Z"
        }
    }
]
```

**Comment by alexyao2015** [comment]
From the looks of it, it seems like you are getting the correct architecture, so something else must be going wrong. Are you able to provide the `docker image inspect` of an addon that does currently function properly? For example, the VSCode extension.

**Comment by Mr-Groch** [comment]
zigbee2mqtt inspect:

```
[
    {
        "Id": "sha256:7c277307bcce7592891ca0f39d9855d075c981eeb6a825468b0eda037a0a2f30",
        "RepoTags": [
            "zigbee2mqtt/zigbee2mqtt-armv7:1.17.0"
        ],
        "RepoDigests": [
            "zigbee2mqtt/zigbee2mqtt-armv7@sha256:28d28de984dd566640f6c228aa5618bdf14025279c0c153593f8dde9701e5221"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2021-01-04T11:48:31.958572228Z",
        "Container": "79e42be9e646ed8f4f2d27800e214e0bb272825d0501cb32e94bb9e4cedfb829",
        "ContainerConfig": {
            "Hostname": "79e42be9e646",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=2",
                "S6_CMD_WAIT_FOR_SERVICES=1"
            ],
            "Cmd": [
                "/bin/ash",
                "-o",
                "pipefail",
                "-c",
                "#(nop) ",
                "LABEL io.hass.version=1.17.0"
            ],
            "Image": "sha256:20d8dbcb334c3eafbb31485696e5fc5bab96ab37449a51a3e2ce7fc758b578bc",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "io.hass.arch": "armv7",
                "io.hass.base.image": "homeassistant/{arch}-base",
                "io.hass.base.name": "alpine",
                "io.hass.base.version": "2021.01.0",
                "io.hass.description": "Zigbee2mqtt add-on",
                "io.hass.name": "Zigbee2mqtt",
                "io.hass.type": "addon",
                "io.hass.url": "https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/tree/master/zigbee2mqtt",
                "io.hass.version": "1.17.0"
            },
            "Shell": [
                "/bin/ash",
                "-o",
                "pipefail",
                "-c"
            ]
        },
        "DockerVersion": "19.03.13+azure",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "S6_BEHAVIOUR_IF_STAGE2_FAILS=2",
                "S6_CMD_WAIT_FOR_SERVICES=1"
            ],
            "Cmd": null,
            "Image": "sha256:20d8dbcb334c3eafbb31485696e5fc5bab96ab37449a51a3e2ce7fc758b578bc",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "io.hass.arch": "armv7",
                "io.hass.base.image": "homeassistant/{arch}-base",
                "io.hass.base.name": "alpine",
                "io.hass.base.version": "2021.01.0",
                "io.hass.description": "Zigbee2mqtt add-on",
                "io.hass.name": "Zigbee2mqtt",
                "io.hass.type": "addon",
                "io.hass.url": "https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/tree/master/zigbee2mqtt",
                "io.hass.version": "1.17.0"
            },
            "Shell": [
                "/bin/ash",
                "-o",
                "pipefail",
                "-c"
            ]
        },
        "Architecture": "arm",
        "Os": "linux",
        "Size": 659536248,
        "VirtualSize": 659536248,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/mnt/data/docker/overlay2/0a4522f49df8a4aaf31d8decdc7391b7f7877d17d5a69adff0528df790ce0e3f/diff:/mnt/data/docker/overlay2/75b2ed38742603b576082e4c4cdcf2a882439b05c48e2055e1661c02b0af7037/diff:/mnt/data/docker/overlay2/274700071db0ec191818607c85d0867bc4e23f0a37414b73dfc7f8bb55c4cea7/diff:/mnt/data/docker/overlay2/3516bdcc1b36966d6d88445f3774a00b899b30a4a30031ec0907f101785a7c95/diff:/mnt/data/docker/overlay2/84db383f8345cad87488862825d1b1cabf57eb98612a70b4bf663ca10e5e23a3/diff:/mnt/data/docker/overlay2/12a153596eb47e233e4196fc3d4afaa92cd4d90fcdd57d71cb84b8158216945f/diff:/mnt/data/docker/overlay2/46bd6e03f936141353052af35c2d2b021ddbd839087fedeae29d1fd43c883565/diff",
                "MergedDir": "/mnt/data/docker/overlay2/ab2cdd913cbfd5ea32e0e5b528bc7fcbc468b22a77ad2ad42f9ec7ddea222dbd/merged",
                "UpperDir": "/mnt/data/docker/overlay2/ab2cdd913cbfd5ea32e0e5b528bc7fcbc468b22a77ad2ad42f9ec7ddea222dbd/diff",
                "WorkDir": "/mnt/data/docker/overlay2/ab2cdd913cbfd5ea32e0e5b528bc7fcbc468b22a77ad2ad42f9ec7ddea222dbd/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:72bbe6b5204e7df9466d6597c4888cf950f0b379bf476a76925feabf17e94aa9",
                "sha256:b589e68b6d6e6ff11b22a776290f52a97fa090eb01fd4a426830ea0961cce7a4",
                "sha256:87d8b86a50d023b72fecc128232540322a1955202cd8e754db60ed6ae584f27d",
                "sha256:caeb3a3510b2c7e18f9a61e0248397af3067861c5351000b8e1ffac9c061b22d",
                "sha256:d5261aff423b65bdc36c44ee5b5020e797eb0a560d91ff29ce1fa46c7b73006e",
                "sha256:963e578d93c8c8d035e328e1ff64ea54243a889e5ad8752dcde2090dcd12e68e",
                "sha256:cbc584a14b46bf12790a1f778c6dfece35cc6f68a5f3ff8e594dc39ad0a07b23",
                "sha256:0f083982b42b2a8465f7a283e1d57b6d2d0d6b7f948ba1dd1b62cdd1d649e9fb"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

**Comment by alexyao2015** [comment]
Are you able to uninstall the addon, reload the repository (supervisor -> add-on store -> three dots at top left -> reload), run `docker system prune -a` using ssh, then reinstall dev?

**Comment by Mr-Groch** [comment]
Still no improvement, after try to start addon:

```
/init: 11: /init: /bin/importas: Exec format error
/init: 12: export: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: bad variable name
```

**Comment by alexyao2015** [comment]
I've just published a new testing image. Please try installing that. You may need to reload the store to be able to see it. Beware, this may take upwards of 30 minutes to 1 hour to fully build and install. This will help to narrow down the issue.

**Comment by Mr-Groch** [comment]
Sorry, can't install from testing:

```
21-01-05 09:29:27 INFO (SyncWorker_7) [supervisor.docker.addon] Starting build for 7c966942/armv7-addon-emulated_hue_dev:testing
21-01-05 09:29:32 ERROR (SyncWorker_7) [supervisor.docker.addon] Can't build 7c966942/armv7-addon-emulated_hue_dev:testing: 400 Client Error for http+docker://localhost/v1.40/build?t=7c966942%2Farmv7-addon-emulated_hue_dev%3Atesting&q=False&nocache=False&rm=False&forcerm=True&pull=True&buildargs=%7B%22BUILD_FROM%22%3A+%22homeassistant%2Farmv7-base%3Alatest%22%2C+%22BUILD_VERSION%22%3A+%22testing%22%2C+%22BUILD_ARCH%22%3A+%22armv7%22%7D&labels=%7B%22io.hass.version%22%3A+%22testing%22%2C+%22io.hass.arch%22%3A+%22armv7%22%2C+%22io.hass.type%22%3A+%22addon%22%2C+%22io.hass.name%22%3A+%22Emulated+HUE+%28testing%29%22%2C+%22io.hass.description%22%3A+%22Hue+Emulation+for+Home+Assistant%22%2C+%22io.hass.url%22%3A+%22https%3A%2F%2Fgithub.com%2Fhass-emulated-hue%2Fcore%22%7D: Bad Request ("Dockerfile parse error line 89: Unknown flag: mount")
```

**Comment by alexyao2015** [comment]
Try installing it now

**Comment by wessller** [comment]
No luck:

/init: 11: /init: /bin/importas: Exec format error
/init: 12: export: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: bad variable name

**Comment by alexyao2015** [comment]
Thanks I believe I've found the problem through that test. Will push a fix out later.

**Comment by Mr-Groch** [comment]
Testing branch won't install - it cashes my RPI just like one of the first releases: #21 after about half hour of building...

**Comment by alexyao2015** [comment]
Yes, I'll push out a fix for this later today. I'll let you know when it's fixed

**Comment by alexyao2015** [comment]
Should be fixed now. Give it a try.

**Comment by Mr-Groch** [comment]
Yes, it is fixed now. dev and stable working. Thank!
