### ISSUE TITLE
Connection issues after restarting Home Assistant

### ISSUE THREAD

**Issue by WolfsWelpe** [hass-emulated-hue/core#88]
**Describe the bug**

Actually idk why this happened but after this error appeared none of the lights
are responding anymore by Hue Entertainment Area. 

**Steps to Reproduce**

I have no Idea?
Maybe some Sort of not closing a connection properly?

**Expected behavior**

**Logs**

```
2021-01-22 00:54:44,322 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-2612715' coro=<EntertainmentAPI.__async_process_light_packet() done, defined at /app/emulated_hue/entertainment.py:106> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/app/emulated_hue/entertainment.py", line 144, in __async_process_light_packet
    await self.hass.async_call_service("light", "turn_on", svc_data)
  File "/usr/local/lib/python3.8/site-packages/hass_client/__init__.py", line 204, in async_call_service
    return await self.__async_send_ws(msg)
TypeError: 'NoneType' object is not callable
2021-01-22 00:54:44,363 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-2612717' coro=<EntertainmentAPI.__async_process_light_packet() done, defined at /app/emulated_hue/entertainment.py:106> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/app/emulated_hue/entertainment.py", line 144, in __async_process_light_packet
    await self.hass.async_call_service("light", "turn_on", svc_data)
  File "/usr/local/lib/python3.8/site-packages/hass_client/__init__.py", line 204, in async_call_service
    return await self.__async_send_ws(msg)
TypeError: 'NoneType' object is not callable
2021-01-22 00:54:44,404 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-2612719' coro=<EntertainmentAPI.__async_process_light_packet() done, defined at /app/emulated_hue/entertainment.py:106> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/app/emulated_hue/entertainment.py", line 144, in __async_process_light_packet
    await self.hass.async_call_service("light", "turn_on", svc_data)
  File "/usr/local/lib/python3.8/site-packages/hass_client/__init__.py", line 204, in async_call_service
    return await self.__async_send_ws(msg)
TypeError: 'NoneType' object is not callable
2021-01-22 00:54:44,445 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-2612721' coro=<EntertainmentAPI.__async_process_light_packet() done, defined at /app/emulated_hue/entertainment.py:106> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/app/emulated_hue/entertainment.py", line 144, in __async_process_light_packet
    await self.hass.async_call_service("light", "turn_on", svc_data)
  File "/usr/local/lib/python3.8/site-packages/hass_client/__init__.py", line 204, in async_call_service
    return await self.__async_send_ws(msg)
TypeError: 'NoneType' object is not callable
2021-01-22 00:54:44,487 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-2612723' coro=<EntertainmentAPI.__async_process_light_packet() done, defined at /app/emulated_hue/entertainment.py:106> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/app/emulated_hue/entertainment.py", line 144, in __async_process_light_packet
    await self.hass.async_call_service("light", "turn_on", svc_data)
  File "/usr/local/lib/python3.8/site-packages/hass_client/__init__.py", line 204, in async_call_service
    return await self.__async_send_ws(msg)
TypeError: 'NoneType' object is not callable
2021-01-22 00:54:44,529 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-2612725' coro=<EntertainmentAPI.__async_process_light_packet() done, defined at /app/emulated_hue/entertainment.py:106> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/app/emulated_hue/entertainment.py", line 144, in __async_process_light_packet
    await self.hass.async_call_service("light", "turn_on", svc_data)
  File "/usr/local/lib/python3.8/site-packages/hass_client/__init__.py", line 204, in async_call_service
    return await self.__async_send_ws(msg)
TypeError: 'NoneType' object is not callable
2021-01-22 00:54:44,550 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-2612726' coro=<EntertainmentAPI.__async_process_light_packet() done, defined at /app/emulated_hue/entertainment.py:106> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/app/emulated_hue/entertainment.py", line 144, in __async_process_light_packet
    await self.hass.async_call_service("light", "turn_on", svc_data)
  File "/usr/local/lib/python3.8/site-packages/hass_client/__init__.py", line 204, in async_call_service
    return await self.__async_send_ws(msg)
TypeError: 'NoneType' object is not callable
2021-01-22 00:54:44,613 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-2612729' coro=<EntertainmentAPI.__async_process_light_packet() done, defined at /app/emulated_hue/entertainment.py:106> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/app/emulated_hue/entertainment.py", line 144, in __async_process_light_packet
    await self.hass.async_call_service("light", "turn_on", svc_data)
  File "/usr/local/lib/python3.8/site-packages/hass_client/__init__.py", line 204, in async_call_service
    return await self.__async_send_ws(msg)
TypeError: 'NoneType' object is not callable
2021-01-22 00:54:44,655 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-2612731' coro=<EntertainmentAPI.__async_process_light_packet() done, defined at /app/emulated_hue/entertainment.py:106> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/app/emulated_hue/entertainment.py", line 144, in __async_process_light_packet
    await self.hass.async_call_service("light", "turn_on", svc_data)
  File "/usr/local/lib/python3.8/site-packages/hass_client/__init__.py", line 204, in async_call_service
    return await self.__async_send_ws(msg)
TypeError: 'NoneType' object is not callable
2021-01-22 00:54:44,676 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-2612732' coro=<EntertainmentAPI.__async_process_light_packet() done, defined at /app/emulated_hue/entertainment.py:106> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/app/emulated_hue/entertainment.py", line 144, in __async_process_light_packet
    await self.hass.async_call_service("light", "turn_on", svc_data)
  File "/usr/local/lib/python3.8/site-packages/hass_client/__init__.py", line 204, in async_call_service
    return await self.__async_send_ws(msg)
TypeError: 'NoneType' object is not callable
2021-01-22 00:54:44,738 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-2612735' coro=<EntertainmentAPI.__async_process_light_packet() done, defined at /app/emulated_hue/entertainment.py:106> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/app/emulated_hue/entertainment.py", line 144, in __async_process_light_packet
    await self.hass.async_call_service("light", "turn_on", svc_data)
  File "/usr/local/lib/python3.8/site-packages/hass_client/__init__.py", line 204, in async_call_service
    return await self.__async_send_ws(msg)
TypeError: 'NoneType' object is not callable
2021-01-22 00:54:44,759 ERROR asyncio -- Task exception was never retrieved
future: <Task finished name='Task-2612736' coro=<EntertainmentAPI.__async_process_light_packet() done, defined at /app/emulated_hue/entertainment.py:106> exception=TypeError("'NoneType' object is not callable")>
Traceback (most recent call last):
  File "/app/emulated_hue/entertainment.py", line 144, in __async_process_light_packet
    await self.hass.async_call_service("light", "turn_on", svc_data)
  File "/usr/local/lib/python3.8/site-packages/hass_client/__init__.py", line 204, in async_call_service
    return await self.__async_send_ws(msg)
TypeError: 'NoneType' object is not callable
```

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
 - Addon version (Ex: stable or dev):  stable
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): HyperV Environment on Windows10
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PC

**Additional context**

I closed Razer Synapse a few times for testing maybe there got something messed up with the connection and its not closed properly?

**Comment by alexyao2015** [comment]
Pretty sure this is #87. Just wipe your config.

**Comment by WolfsWelpe** [comment]
Okay I will give it a try, I just want to say that I haven't changed anything at HassIO like deleting lights.

**Comment by alexyao2015** [comment]
Not sure then but will need replication steps to be able to debug/fix it. If clearing the config worked, try redoing the steps that caused it to break to find out how to reproduce it.

**Comment by WolfsWelpe** [comment]
Actually im not able to get this error again. Actually I don't know what happened there :/ Im closing it for now and if I know more I post it in here.

**Comment by WolfsWelpe** [comment]
Hello,
I have now found out how the error occurs. Quite simple:
While the addon is running in general and you restart HomeAssistant in the meantime, this error appears afterwards in the log of the addon when you do something with Hue Entertainment Area like connecting or when the already connected software (before the restart) wants to change a light.

**Comment by alexyao2015** [comment]
So you
1) Start add-on
2) restart add-on
3) open entertainment area??

I definitely don't get these issues when I do that. Please provide step by step instructions for how to get the error

**Comment by WolfsWelpe** [comment]
Not exactly ^^
Ok here we go;
1. Start Add-On
2. Restart Home Assistant (Not the addon, its running the whole time)
3. After Home Assistant is back up every Action (Not just HUe Entertainment Area) like changing a light manually will not work anymore and the "NoneType" Error occurs. Starting Hue Entertainment Area or the usage of already connected ones will not work anymore.

Fix:
Restart of the Addon.

**Comment by WolfsWelpe** [comment]
So do you get the issue as well?

**Comment by DavidFFerreira** [comment]
same error, fresh install, first try

**Comment by alexyao2015** [comment]
Great! This appears to be an actual bug with `hass-client`. Logs show it getting stuck connecting to hassio 

```
hass-client -- Connecting to hassio/homeassistant
```

Will need to implement a timeout and retry attempt during connection. @marcelveldt Can you look into adding a timeout/backoff mechanism to connections in `hass-client`?

In the meantime, this is a rather harmless and low priority issue to fix as it's resolved simply by a restart of the addon. 

@DavidFFerreira Your issue seems to be unrelated to this issue. Please create a discussion/issue and be sure to include as much detail as possible.

**Comment by marcelveldt** [comment]
I ran into this myself couple of days ago. I'll fix the issue in the hass-client lib within a few days.
Thanks for the reminder ;-)
