### ISSUE TITLE
Missing name in group

### ISSUE THREAD

**Issue by zewelor** [hass-emulated-hue/core#91]
**Describe the bug**

Looks like group created from TV, and saved in emulated_hue.json, doesn't have a name attribute. I've tried to fix it manually adding ```name: ""``` into that group and it worked.

**Steps to Reproduce**

Testy fresh install of emulated_hue. Setup it up with tv, then turn ambilight hue on.

**Expected behavior**

**Logs**

```
emulated-hue                      | 2021-01-23 16:09:46,827 DEBUG emulated_hue.api -- Start Entertainment mode for group 7 - params: {'stream': {'active': True}}
emulated-hue                      | 2021-01-23 16:09:46,834 INFO  emulated_hue.entertainment -- Start HUE Entertainment Service on UDP port 2100.
emulated-hue                      | 2021-01-23 16:09:46,835 ERROR asyncio -- Task exception was never retrieved
emulated-hue                      | future: <Task finished name='Task-1177' coro=<EntertainmentAPI.async_run() done, defined at /app/emulated_hue/entertainment.py:53> exception=KeyError('name')>
emulated-hue                      | Traceback (most recent call last):
emulated-hue                      |   File "/app/emulated_hue/entertainment.py", line 60, in async_run
emulated-hue                      |     HASS_SENSOR, "on", {"room": self.group_details["name"]}
emulated-hue                      | KeyError: 'name'
```

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
 - Addon version (Ex: stable or dev): 
    - Value of "tag_commit_or_branch" if using dev: 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Additional context**

**Comment by alexyao2015** [comment]
Great thanks! Can you post the corresponding request that created the group? You can get that by turning on verbose logging.

**Comment by zewelor** [comment]
I hope this will be it ?

```
emulated-hue                      | 2021-01-25 16:02:25,812 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/36                                           [390/94889]
emulated-hue                      | 2021-01-25 16:02:25,830 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/37
emulated-hue                      | 2021-01-25 16:02:25,843 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/38
emulated-hue                      | 2021-01-25 16:02:25,857 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/39
emulated-hue                      | 2021-01-25 16:02:25,871 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/40
emulated-hue                      | 2021-01-25 16:02:25,887 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/41
emulated-hue                      | 2021-01-25 16:02:25,900 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/42
emulated-hue                      | 2021-01-25 16:02:25,913 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/43
emulated-hue                      | 2021-01-25 16:02:25,926 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/44
emulated-hue                      | 2021-01-25 16:02:25,943 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/45
emulated-hue                      | 2021-01-25 16:02:25,957 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/46
emulated-hue                      | 2021-01-25 16:02:25,973 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/47
emulated-hue                      | 2021-01-25 16:02:25,988 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/48
emulated-hue                      | 2021-01-25 16:02:26,015 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/49
emulated-hue                      | 2021-01-25 16:02:26,056 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/50
emulated-hue                      | 2021-01-25 16:02:26,073 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/51
emulated-hue                      | 2021-01-25 16:02:26,091 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/52
emulated-hue                      | 2021-01-25 16:02:26,110 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/53
emulated-hue                      | 2021-01-25 16:02:26,130 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/54
emulated-hue                      | 2021-01-25 16:02:26,146 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/55
emulated-hue                      | 2021-01-25 16:02:26,158 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/56
emulated-hue                      | 2021-01-25 16:02:26,172 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/57
emulated-hue                      | 2021-01-25 16:02:26,187 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/58
emulated-hue                      | 2021-01-25 16:02:26,202 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/59
emulated-hue                      | 2021-01-25 16:02:26,217 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/60
emulated-hue                      | 2021-01-25 16:02:26,231 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/61
emulated-hue                      | 2021-01-25 16:02:26,249 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/62
emulated-hue                      | 2021-01-25 16:02:26,267 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/63
emulated-hue                      | 2021-01-25 16:02:26,286 DEBUG emulated_hue.api -- [192.168.1.12] POST /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/
emulated-hue                      | 2021-01-25 16:02:26,326 DEBUG emulated_hue.api -- {'lights': ['18', '19'], 'type': 'Entertainment', 'class': 'TV'}
emulated-hue                      | 2021-01-25 16:02:26,449 DEBUG emulated_hue.api -- [192.168.1.12] PUT /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/7
emulated-hue                      | 2021-01-25 16:02:26,458 DEBUG emulated_hue.api -- {'stream': {'active': False}}
emulated-hue                      | 2021-01-25 16:02:26,458 INFO  emulated_hue.api -- Stop Entertainment mode for group 7 - params: {'stream': {'active': False}}
emulated-hue                      | 2021-01-25 16:02:26,468 DEBUG emulated_hue.api -- [192.168.1.12] GET /api/d135dd5f-0785-461c-9836-2b33f1e91524/capabilities
emulated-hue                      | 2021-01-25 16:02:26,486 DEBUG emulated_hue.api -- [192.168.1.12] PUT /api/d135dd5f-0785-461c-9836-2b33f1e91524/groups/7
emulated-hue                      | 2021-01-25 16:02:26,496 DEBUG emulated_hue.api -- {'stream': {'active': True}}
emulated-hue                      | 2021-01-25 16:02:26,496 DEBUG emulated_hue.api -- Start Entertainment mode for group 7 - params: {'stream': {'active': True}}
emulated-hue                      | 2021-01-25 16:02:26,506 INFO  emulated_hue.entertainment -- Start HUE Entertainment Service on UDP port 2100.
emulated-hue                      | 2021-01-25 16:02:26,506 ERROR asyncio -- Task exception was never retrieved
emulated-hue                      | future: <Task finished name='Task-1467' coro=<EntertainmentAPI.async_run() done, defined at /app/emulated_hue/entertainment.py:53> exception=KeyError('name')>
emulated-hue                      | Traceback (most recent call last):
emulated-hue                      |   File "/app/emulated_hue/entertainment.py", line 60, in async_run
emulated-hue                      |     HASS_SENSOR, "on", {"room": self.group_details["name"]}
emulated-hue                      | KeyError: 'name'
```

**Comment by alexyao2015** [comment]
It seems like we need to add a name to the group during creation as that's what the official bridge seems to do. Furthermore, we need to ensure duplicate group names do not occur by validating group names and appending a number if it's a duplicate.
